name = "ctx-do"
route = { pattern = "*/*", zone_name = "ctx.do" }
main = "worker.js"
usage_model = "unbound"
compatibility_date = "2022-10-28"
node_compat = true

services = [
  { binding = "APIKEYS", service = "apikeys-do", environment = "production" },
  { binding = "JWT", service = "jwt-do", environment = "production" }
]

[[unsafe.bindings]]
type = "analytics_engine"
name = "INTERACTIONS"
