name = "ctx-do"
route = { pattern = "*/*", zone_name = "ctx.do" }
main = "worker.js"
usage_model = "unbound"
compatibility_date = "2023-07-01"
logpush = true
node_compat = true

tail_consumers = [{service = "tail", environment = "production"}]

services = [
  { binding = "APIKEYS", service = "apikeys-do", environment = "production" },
  { binding = "JWT", service = "jwt-do", environment = "production" }
]

[[unsafe.bindings]]
type = "analytics_engine"
name = "INTERACTIONS"
