name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Get dependencies
        run: 'yarn'
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
      - name: Prettier Action
        uses: creyD/prettier_action@v4.2'
        with:
          samecommit: true
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
